/* AI provider abstraction — D-007 pillar.
 * Surfaces extraction (PDF -> structured JSON) and chat (conversational Q&A)
 * with a free-tier guard, mock fallback, SHA-256 keyed cache and
 * call-level observability.
 *
 * Provider selection by env: AI_PROVIDER=gemini|groq|mock (default: mock).
 * Free-tier guard (AI_TIER=free) rejects any extract() request whose
 * payload SHA is not in the demo allowlist.
 */

import type { z } from "zod";
import { mockProvider } from "./mock";
import { extractWithGemini, chatWithGemini } from "./gemini";
import { chatWithGroq } from "./groq";
import { extractionCache } from "./cache";
import { logAICall } from "./observability";
import { sha256Hex } from "./hash";

export type AIProviderName = "gemini" | "groq" | "mock";

export type DocKind = "invoice" | "bl" | "packing_list" | "pedimento" | "mve" | "cfdi" | "coo" | "carta_porte";

export interface AIExtractRequest<T> {
  pdfBytes: Uint8Array;
  schema: z.ZodSchema<T>;
  schemaVersion: string;
  docKind: DocKind;
  /** Pre-computed SHA hex (skip hashing if you already have it). */
  pdfSha?: string;
}

export interface AIExtractResponse<T> {
  data: T;
  model: string;
  latencyMs: number;
  cached: boolean;
  confidencePerField?: Record<string, number>;
}

export interface AIChatMessage {
  role: "system" | "user" | "assistant";
  content: string;
}

export interface AIChatRequest {
  messages: AIChatMessage[];
  context?: string;
}

export interface AIChatResponse {
  text: string;
  model: string;
  latencyMs: number;
  relatedLessons?: string[];
  suggestedAction?: string;
}

function getProviderName(): AIProviderName {
  const env = (process.env.AI_PROVIDER ?? "mock").toLowerCase();
  if (env === "gemini" || env === "groq") return env;
  return "mock";
}

function getTier(): "free" | "paid" {
  return process.env.AI_TIER === "paid" ? "paid" : "free";
}

/* Demo PDF allowlist — only files served from /public/sample-documents/ are
 * allowed to hit a real LLM on the free tier. Production / paid tier disables
 * this guard. Hashes computed at request time and compared against the
 * snapshot below. The snapshot is regenerated by `npm run ai:warm-cache`
 * (TODO) — until then this list is empty and *any* free-tier extract call
 * falls back to mock (the safe default). */
const DEMO_SHA_ALLOWLIST = new Set<string>([
  // Populate via warm-cache script. Empty = nothing is allowed -> mock fallback.
]);

async function validateDemoTier(pdfSha: string): Promise<boolean> {
  if (getTier() === "paid") return true;
  return DEMO_SHA_ALLOWLIST.has(pdfSha);
}

export async function extract<T>(req: AIExtractRequest<T>): Promise<AIExtractResponse<T>> {
  const start = performance.now();
  const provider = getProviderName();
  const pdfSha = req.pdfSha ?? (await sha256Hex(req.pdfBytes));
  const cacheKey = `${pdfSha}:${req.schemaVersion}:${req.docKind}`;

  // 1. Cache hit -> return immediately.
  const cached = extractionCache.get<T>(cacheKey);
  if (cached) {
    const latencyMs = performance.now() - start;
    logAICall({
      surface: "documents.extract",
      provider,
      model: cached.model,
      docKind: req.docKind,
      pdfSha,
      latencyMs,
      cached: true,
      success: true,
    });
    return { ...cached, latencyMs, cached: true };
  }

  // 2. Free-tier guard. Real customer PDFs must NOT hit a free LLM.
  const allowed = await validateDemoTier(pdfSha);
  if (!allowed && provider !== "mock") {
    // Fall back to mock + warn in logs (don't throw — the app must keep working).
    const result = await mockProvider.extract(req);
    extractionCache.set(cacheKey, result);
    logAICall({
      surface: "documents.extract",
      provider: "mock",
      model: result.model,
      docKind: req.docKind,
      pdfSha,
      latencyMs: performance.now() - start,
      cached: false,
      success: true,
      errorCode: "tier_guard_fallback",
    });
    return { ...result, cached: false };
  }

  // 3. Provider path.
  try {
    let result: AIExtractResponse<T>;
    if (provider === "gemini") {
      result = await extractWithGemini(req);
    } else {
      result = await mockProvider.extract(req);
    }
    extractionCache.set(cacheKey, result);
    logAICall({
      surface: "documents.extract",
      provider,
      model: result.model,
      docKind: req.docKind,
      pdfSha,
      latencyMs: performance.now() - start,
      cached: false,
      success: true,
    });
    return result;
  } catch (err) {
    // 4. Hard failure -> mock fallback (the demo must never break).
    const result = await mockProvider.extract(req);
    extractionCache.set(cacheKey, result);
    logAICall({
      surface: "documents.extract",
      provider: "mock",
      model: result.model,
      docKind: req.docKind,
      pdfSha,
      latencyMs: performance.now() - start,
      cached: false,
      success: false,
      errorCode: err instanceof Error ? err.message.slice(0, 64) : "unknown_error",
    });
    return result;
  }
}

export async function chat(req: AIChatRequest): Promise<AIChatResponse> {
  const start = performance.now();
  const provider = getProviderName();
  try {
    let result: AIChatResponse;
    if (provider === "groq") {
      result = await chatWithGroq(req);
    } else if (provider === "gemini") {
      result = await chatWithGemini(req);
    } else {
      result = await mockProvider.chat(req);
    }
    logAICall({
      surface: "tutor.chat",
      provider,
      model: result.model,
      latencyMs: performance.now() - start,
      cached: false,
      success: true,
    });
    return result;
  } catch (err) {
    const result = await mockProvider.chat(req);
    logAICall({
      surface: "tutor.chat",
      provider: "mock",
      model: result.model,
      latencyMs: performance.now() - start,
      cached: false,
      success: false,
      errorCode: err instanceof Error ? err.message.slice(0, 64) : "unknown_error",
    });
    return result;
  }
}

/* Re-exports for convenience. */
export { sha256Hex } from "./hash";
export { extractionCache } from "./cache";
